"""empty message

Revision ID: 35ffca81394b
Revises: 39fb9b606de3
Create Date: 2014-06-04 09:34:22.650192

"""

# revision identifiers, used by Alembic.
revision = '35ffca81394b'
down_revision = '39fb9b606de3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wanttracking', sa.Column('user_typ_id', sa.Integer(), nullable=False))
    op.drop_constraint("wanttracking_ibfk_3","wanttracking",type_="foreignkey")
    op.drop_index('i_WantTracking_user', table_name='wanttracking')
    op.create_index('i_WantTracking_user', 'wanttracking', ['user_typ_id', 'user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('i_WantTracking_user', table_name='wanttracking')
    op.create_index('i_WantTracking_user', 'wanttracking', ['user_id'], unique=False)
    op.drop_column('wanttracking', 'user_typ_id')
    ### end Alembic commands ###
