"""empty message

Revision ID: 39fb9b606de3
Revises: 4ce51ded186a
Create Date: 2014-06-01 15:53:29.332084

"""

# revision identifiers, used by Alembic.
revision = '39fb9b606de3'
down_revision = '45e9eb549456'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.elements import False_

from sqlalchemy.sql import expression
from sqlalchemy.ext.compiler import compiles

class sql_false(expression.ColumnElement):
    pass

@compiles(sql_false)
def default_false(element, compiler, **kw):
    return "false"

@compiles(sql_false, 'mssql')
@compiles(sql_false, 'mysql')
@compiles(sql_false, 'oracle')
def int_false(element, compiler, **kw):
    return "0"

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('inherit_parent', sa.Boolean(), server_default=sql_false(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'inherit_parent')
    ### end Alembic commands ###
