"""empty message

Revision ID: 39fb9b606de3
Revises: 4ce51ded186a
Create Date: 2014-06-01 15:53:29.332084

"""

# revision identifiers, used by Alembic.
revision = '39fb9b606de3'
down_revision = '4ce51ded186a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('inherit_parent', sa.Boolean(), server_default=u'FALSE', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'inherit_parent')
    ### end Alembic commands ###
