"""empty message

Revision ID: 45e9eb549456
Revises: None
Create Date: 2014-05-28 17:44:39.408934

"""

# revision identifiers, used by Alembic.
revision = '45e9eb549456'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
