"""empty message

Revision ID: 4abb4067e77e
Revises: 35ffca81394b
Create Date: 2014-06-18 07:35:03.487082

"""

# revision identifiers, used by Alembic.
revision = '4abb4067e77e'
down_revision = '35ffca81394b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('config_id', sa.Integer(), nullable=False))
    op.create_index('i_User_config', 'users', ['config_id'], unique=False)
    op.create_foreign_key("fk_user_config", 'users', 'configdata', ['config_id'], ['id'])

    ### end alembic commands ###


def downgrade():
    ### commands auto generated by alembic - please adjust! ###
    op.drop_constraint('fk_user_config','user')
    op.drop_index('i_user_config', table_name='users')
    op.drop_column('users', 'config_id')
    ### end Alembic commands ###
