"""empty message

Revision ID: 4ce51ded186a
Revises: 45e9eb549456
Create Date: 2014-05-31 18:45:56.422102

"""

# revision identifiers, used by Alembic.
revision = '4ce51ded186a'
down_revision = '45e9eb549456'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('inherit_parent', sa.Boolean(), nullable=False, default=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'inherit_parent')
    ### end Alembic commands ###
