"""empty message

Revision ID: 766e43008e0
Revises: 39fb9b606de3
Create Date: 2014-06-04 03:47:34.733207

"""

# revision identifiers, used by Alembic.
revision = '766e43008e0'
down_revision = '39fb9b606de3'

from alembic import op
import sqlalchemy as sa

from pybble.core.models.user import User
USER=User.type.id

def upgrade():
    op.add_column('wanttracking', sa.Column('user_typ_id', sa.Integer(), nullable=False,server_default=str(USER)))
    op.drop_index('i_WantTracking_user', table_name='wanttracking')
    op.create_index('i_WantTracking_user', 'wanttracking', ['user_typ_id', 'user_id'], unique=False)
    op.alter_column('wanttracking', sa.Column('user_typ_id', sa.Integer(), nullable=False,server_default="NULL"))


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('i_WantTracking_user', table_name='wanttracking')
    op.create_index('i_WantTracking_user', 'wanttracking', ['user_id'], unique=False)
    op.drop_column('wanttracking', 'user_typ_id')
    ### end Alembic commands ###
